### ISSUE TITLE
Add option to params.toml

### ISSUE THREAD

**Issue by sysadmin-info** [martignoni/hugo-cloak-email#13]
I need this to be added in params.toml

where I have defined it this way

email = "name@example.com"

See my website [sysadmin on netlify](https://sysadmin-info.netlify.app/)

and 

my repo at github [sysadmin repo](https://github.com/sysadmin-info/sysadmin.info.pl)

**Comment by martignoni** [comment]
What you ask for is not the intended use of the shortcode. Maybe you can pass your config parameter to the shortcode? Ask on the Hugo forum.
