### ISSUE TITLE
Add custom text

### ISSUE THREAD

**Issue by chris-79** [martignoni/hugo-cloak-email#2]
First of all, this is **GREAT!**

Second: It'd be super nice to be able to use custom text instead of just the address.

I'm thinking something like:
```
{{< cloakemail display="Email Us" address="info@example.com" class="button" >}}
```

to render the equivalent of:
```
<a href="mailto:info@example.com" class="button">Email Us</a>
```

😃

**Comment by martignoni** [comment]
Nice idea. I'll give it a shot when I've some time.

**Comment by martignoni** [comment]
Commit af51ce4 closes this. Thanks @chris-79 for the good idea.
