### ISSUE TITLE
Shortcode only works with text strings containing '@' in it

### ISSUE THREAD

**Issue by solrayc** [martignoni/hugo-cloak-email#5]
Once I successfully cloaked email on contact page, I gained confidence to add other cloaked contact info, like `tel:phonenumber` and `skype:username`. 

I thought I could cloak it just the same, but it turns out the shortcode only works with text strings containing '@' in it:
```
{{- $parts := split $address "@" -}}
{{- $user := (index $parts 0) -}}
{{- $domain := (index $parts 1) -}}
```
I'm not a coder, but it looks like splitting email into parts is essential to the way cloaking works. Perhaps splitting of text strings can be done without `@` symbol?

Idea 1: split text at the certain symbol position, lets say on the 5th symbol. This way user can cloak anything they want.
Idea 2: split text at `:`, so user can cloak `mailto:` `skype:` `tel:` `ftp:` or any other link.

Thank you for your shortcode component, appreciate it.

**Comment by martignoni** [comment]
You should use the parameter `protocol` to cloak other URL schemes such as `tel` and `skype`. See the README file for such usage.

However, this is a bug indeed, since one should be able to indicate an `address` without `@` char.

**Comment by martignoni** [comment]
Fixed. Thank you @solrayc for the report.

**Comment by solrayc** [comment]
Your fix works, thank you!
