### ISSUE TITLE
Hide ?Subject=Subject in text with disabled Java Script

### ISSUE THREAD

**Issue by szpak** [martignoni/hugo-cloak-email#8]
I like your shortcode/theme component. I have one improvement proposal.

Having mailto defined as `foo@example.com?Subject=Message` it would be nice to remove `?Subject...` in the address rendered with disabled Java Script (to keep just en email address).

**Comment by szpak** [comment]
In fact, probably also in the Java Script enabled variant the sufix should be ommitted (to do not be displayed if `message` is skipped).

**Comment by martignoni** [comment]
Did you try to workaround this using option `display="..."`?

**Comment by szpak** [comment]
Yes, display works fine for Java Script enabled version. However, I cannot put `foo@example.com` there as it would be kept in the source as plain text :).

`display` doesn't work at all with Java Script disabled.

**Comment by martignoni** [comment]
> However, I cannot put foo@example.com there as it would be kept in the source as plain text :)

Sure enough.

> `display` doesn't work at all with Java Script disabled.

Yes, but this shortcode doesn't work at all without JavaScript, so you should enable it. Other uses are not supported.

Anyway, I'll add this feature shortly.

**Comment by szpak** [comment]
Thanks for tuning up the Java Script enabled version.

Regarding the fallback method (probably quite rare to see I have to admit), it would be probably necessary (although I may misunderstood how it currently works) to add another optional parameter to shortcode which - if defined - would be taken info account to generate the mailto full URI. For example:

```
{{< cloakemail address="foo@example.com" extraUriParams="?Subject=Subject" >}}
```
Nevertheless, it's a corner case, if you think it's not worth to do that, feel free to skip it.

**Comment by martignoni** [comment]
Good idea. I'll have a look if it's not too complex to do.

**Comment by szpak** [comment]
Just tested it works flawlessly. Thanks!
